crates/ef-testing/src/models/case.rs

Time spent on this PR: .1 
Resolves: #<Issue number>
-   [ ] Bugfix
devs can specify which subcase(s) to run via specifying in the format of <filename_without_extension>_subcase_fork
for example:
```
RUN_SPECIFIC_TESTS=mul_d8g0v0_Shanghai,add_d0g0v0_Shanghai cargo test -p ef-testing --features ef-tests -- --nocapture
```
-   [ ] Yes
-   [X] No

allow devs to specify which specific subcase to run

---

crates/ef-testing/src/lib.rs
crates/ef-testing/src/models/case.rs
crates/ef-testing/src/traits/mod.rs

Make the `should_skip` method a static of `BlockChainTest`, filtering only on the particular test name. Further updates could be done to filter on subtests.
Resolves: #23 
-   [ ] Bugfix
-   [x] Refactoring (no functional changes, no API changes)
`shoud_skip` is made into a static method.
-   [ ] Yes
-   [x] No

refactor: should skip static

---

crates/ef-testing/src/storage/contract.rs
crates/ef-testing/src/storage/eoa.rs
crates/ef-testing/src/storage/mod.rs

Fixes the pre state of the eoa and contract accounts by adding `evm_address` and `is_initialized`.
Resolves: #48 
-   [x] Bugfix
The pre state of the runner is correctly set.
-   [ ] Yes
-   [x] No

fix: pre state

---

crates/ef-testing/src/storage/kakarot.rs
crates/ef-testing/src/storage/mod.rs

Adds the mapping from evm to starknet address in the pre state, which was added in Kakarot in commit [b6619ad](https://github.com/kkrt-labs/kakarot/commit/b6619adb6092984f4c6b4fa512ebf07ec8d47299).
Resolves: #73 
-   [x] Bugfix
Can run all previous passing tests.
-   [ ] Yes
-   [x] No

fix: add evm -> starknet address in pre state

---

crates/ef-testing/src/bin/fetch_commit_kakarot.rs
crates/ef-testing/src/bin/fetch_dump_katana.rs
crates/ef-testing/src/models/case.rs
crates/ef-testing/tests/tests.rs

Adds the `VMTests` to the current runner, with all skipped tests linked to a PR.
Time spent on this PR: 3 days
Resolves: #28 
-   [ ] Bugfix
Runner can run `VMTests`.
-   [ ] Yes
-   [x] No

feat: add vmtests

---

crates/ef-testing/src/models/case.rs
crates/ef-testing/tests/tests.rs

Time spent on this PR: 0
Resolves: #77 
-   [ ] Bugfix
-   [X] Feature
- Add  `stSLoadTest` to ef tests
- Marking `sloadGasCost.json` to skip due to current gas accounting, see https://github.com/kkrt-labs/ef-tests/issues/36 and failing test [pr](https://github.com/kkrt-labs/kakarot/pull/733)
-   [ ] Yes
-   [X] No

feat: add stSLoadTest

---

docs/CONTRIBUTING.md

Resolves: #83
-   [ ] Bugfix
-   [x] Documentation content changes
-   [ ] Yes
-   [x] No

feat: contributor guide

---

Cargo.lock
Cargo.toml
crates/sequencer/Cargo.toml
crates/sequencer/src/config.rs
crates/sequencer/src/lib.rs
crates/sequencer/src/sequencer.rs
crates/sequencer/src/state.rs

Defines the main outline for the test sequencer.
Resolves: #103 
-   [ ] Bugfix
Have a test sequencer crate in order to set the outline for the sequencer.
-   [ ] Yes
-   [x] No

feat: first draft for sequencer

---

Cargo.toml
Makefile
README.md
crates/ef-testing/Cargo.toml
crates/ef-testing/src/bin/fetch_dump_katana.rs
crates/ef-testing/src/bin/fetch_kakarot_submodule_commit.rs
crates/ef-testing/src/models/case.rs
crates/ef-testing/src/models/error.rs
crates/ef-testing/src/models/result.rs
crates/ef-testing/src/models/suite.rs
crates/ef-testing/src/storage/mod.rs
crates/ef-testing/src/storage/models.rs
crates/ef-testing/src/traits/mod.rs
crates/ef-testing/src/utils/assert.rs
crates/ef-testing/src/utils/io.rs
crates/ef-testing/tests/tests.rs

Time spent on this PR: 0.1day
Resolves #81 
-   [ ] Bugfix
-   [x] Documentation content changes
-   [ ] Yes
-   [x] No

refactor: refactor according to clippy pedantic recommendation and add more documentation

---

crates/ef-testing/src/models/case.rs
crates/ef-testing/tests/tests.rs

Resolves: #94 
-   [ ] Bugfix
This PR adds `stInitCode` tests to the test runner.
-   [ ] Yes
-   [x] No

feat: add `stInitCode` tests to the runner

---

crates/ef-testing/tests/tests.rs

Resolves: #93 
-   [ ] Bugfix
-   [ ] Yes
-   [x] No

feat: log tests all pass

---

README.md

Time spent on this PR: 30m
Resolves: N/A
-   [ ] Bugfix
-   [x] Documentation content changes
I've added a bit of context to the README to help new contributors (like me).
-   [ ] Yes
-   [x] No

Doc: Improve readme

---

Cargo.lock
Cargo.toml
Makefile
crates/ef-testing/src/models/case.rs
crates/ef-testing/tests/tests.rs

Begins work on #89 
-   [ ] Bugfix
-   [ ] Yes
-   [x] No

feat: add stBadOpcode

---

blockchain-tests-skip.yml
crates/ef-testing/tests/tests.rs

#359 
-   [ ] Bugfix
-   [ ] Yes
-   [x] No

add `stNonZeroCallsTest` testsuite

---

blockchain-tests-skip.yml
crates/ef-testing/tests/tests.rs

#349 
-   [ ] Bugfix
-   [ ] Yes
-   [x] No

add `stMemoryStressTest` testsuite

---

blockchain-tests-skip.yml
crates/ef-testing/tests/tests.rs

Time spent on this PR: 30m
#342 
-   [ ] Bugfix
-   [ ] Yes
-   [x] No

add `stEIP150singleCodeGasPrices` testsuite

---

blockchain-tests-skip.yml
crates/ef-testing/tests/tests.rs

Time spent on this PR: 15min
#427 
-   [ ] Bugfix
-   [ ] Yes
-   [x] No

add `stWalletTest` testsuite

---

blockchain-tests-skip.yml
crates/ef-testing/tests/tests.rs

Time spent on this PR: 15min
#446 
-   [ ] Bugfix
-   [ ] Yes
-   [x] No

add `stTransactionTest` testsuite

---

.github/workflows/test.yml
.vscode/extensions.json
.vscode/settings.json
Makefile
README.md
crates/ef-testing/src/models/result.rs
crates/sequencer/src/sequencer.rs
docs/CONTRIBUTING.md

Cairo stack trace is displayed with line break.
When targeting a single test, no other tests are marked as `Passed`.
No redundant logging of the test run.

Improve test logging

---

blockchain-tests-skip.yml

The 2 added tests were probably passing before due to a VM error and consequently no state change.
After the return_data fix, the Cairo VM doesn't revert anymore and the tests are failing because of no proper gas accounting.

Unskip passing and add newly failing due to GAS

---

crates/ef-testing/src/evm_sequencer/evm_state.rs
crates/ef-testing/src/evm_sequencer/mod.rs
crates/ef-testing/src/evm_sequencer/types.rs
crates/ef-testing/src/evm_sequencer/utils.rs
crates/sequencer/src/commit.rs
crates/sequencer/src/sequencer.rs
crates/sequencer/src/state.rs
crates/sequencer/src/transaction.rs

Adds rust doc to the sequencer and Kakarot sequencer.
Resolves: #469 
Adds rustdoc.

docs: add rust doc

---

blockchain-tests-skip.yml

See https://github.com/kkrt-labs/kakarot/pull/769
The REVERT refacto is still partial and needs to handle funds. To make the PR not too big, let's skip these tests first, and unskip once it's fixed.

Skip REVERT involding balance

---

.trunk/trunk.yaml
Cargo.lock
Cargo.toml
crates/ef-testing/src/evm_sequencer/evm_state.rs
crates/ef-testing/src/evm_sequencer/mod.rs
crates/sequencer/src/sequencer.rs

This pr enables our sequencer to work on top of our own blockifier and cairo-vm fork.
Resolves: #546 
The codebase has been rebased on top of our own blockifier and cairo-vm fork.

Feat: rebase sequencer on blockifier fork

---

.vscode/settings.json
Makefile
crates/ef-testing/Cargo.toml
crates/ef-testing/build.rs

Time spent on this PR: 0.5 day
Resolves: #NA
Adds a CI feature flag in order to compile all the integration tests under one crate, allowing to take full advantage of the `cargo test` parallelism and avoiding the compilation of one binary per integration test file.

feat: accelerate ci

---

crates/ef-testing/src/evm_sequencer/evm_state/mod.rs
crates/ef-testing/src/evm_sequencer/evm_state/v0.rs
crates/ef-testing/src/evm_sequencer/evm_state/v1.rs
crates/ef-testing/src/models/case.rs

Resolves: #650
Sets the coinbase address and the base fee in the storage of Kakarot v0.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/ef-tests/652)

feat: add coinbase base fee

---

crates/ef-testing/src/evm_sequencer/account/mod.rs
crates/ef-testing/src/evm_sequencer/account/v0.rs
crates/ef-testing/src/evm_sequencer/account/v1.rs
crates/ef-testing/src/evm_sequencer/evm_state/v0.rs
crates/ef-testing/src/evm_sequencer/evm_state/v1.rs
crates/ef-testing/src/models/case.rs
crates/ef-testing/src/models/result.rs

Time spent on this PR: 0.2d
Only the sender of a transaction should be an EOA - otherwise, this creates conflicts when loading accounts assumed to be EOAs because they have no code or storage, but they're just CAs waiting to be deployed and are in state because of a non-empty balance.

feat: only sender account is an EOA in tests

---

Cargo.lock
Cargo.toml
crates/sequencer/Cargo.toml
crates/sequencer/src/serde.rs
crates/sequencer/src/state.rs

This Pull Request updates the sequencer crate to use the hashbrown crate for hash maps instead of rustc_hash.
Time spent on this PR: one hour
Resolves: #686

dev: use the hashbrown crate for hashmap

---

crates/ef-testing/src/evm_sequencer/account/mod.rs
crates/ef-testing/src/evm_sequencer/account/v0.rs
crates/ef-testing/src/evm_sequencer/account/v1.rs
crates/ef-testing/src/evm_sequencer/evm_state/v1.rs
crates/ef-testing/src/evm_sequencer/utils.rs

feat: pack calldata for v0 txs

---

crates/ef-testing/src/evm_sequencer/account/mod.rs
crates/ef-testing/src/evm_sequencer/account/v0.rs
crates/ef-testing/src/evm_sequencer/account/v1.rs
crates/ef-testing/src/evm_sequencer/constants.rs
crates/ef-testing/src/evm_sequencer/evm_state/mod.rs
crates/ef-testing/src/evm_sequencer/evm_state/v0.rs
crates/ef-testing/src/evm_sequencer/evm_state/v1.rs
crates/ef-testing/src/models/case.rs

Linked to https://github.com/kkrt-labs/kakarot/pull/1309#issuecomment-2255276974
Code hash is set in storage when handling the pre state

feat: set code hash in pre state

---

crates/ef-testing/src/evm_sequencer/account/v0.rs
crates/ef-testing/src/evm_sequencer/constants.rs

Resolves: https://github.com/kkrt-labs/kakarot/issues/1347

refactor: remove Account_jumpdests_initialized

---

.gitignore
crates/ef-testing/src/evm_sequencer/account/v0.rs
crates/ef-testing/src/evm_sequencer/account/v1.rs
crates/ef-testing/src/evm_sequencer/constants.rs
crates/ef-testing/src/evm_sequencer/evm_state/v1.rs
crates/ef-testing/src/evm_sequencer/utils.rs

fix: ssj can run again

---

Makefile
crates/ef-testing/src/evm_sequencer/account/v1.rs
crates/ef-testing/src/evm_sequencer/evm_state/v1.rs
crates/ef-testing/src/evm_sequencer/sequencer/v0.rs

Updates Makefile to reflect artifact changes created by SSJ.
Also shushes unused item warnings.

dev: update makefile

---

Cargo.lock
Cargo.toml
crates/ef-testing/Cargo.toml
crates/ef-testing/src/models/case.rs

We want to get rid of ethers dependencies in favor of alloys.

rm `ethers-signers` in favor of `alloy-signer-local`

---

crates/ef-testing/src/evm_sequencer/sequencer/resources/versioned_constants.json
crates/sequencer/src/resources/versioned_constants.json

The file used was for update 0.13.1.1, while the blockifier fork we use was version 0.13.2. This caused some issues with the pricing of syscalls.

chore: bump versioned_constants.json to 0.13.2

---

Cargo.lock
Cargo.toml

- Bump of some crates
- Rust is smart enough to manage versions itself, so it is not desirable to specify exact versioning.

bump some deps and not precise versioning

---

.trunk/trunk.yaml
crates/ef-testing/src/evm_sequencer/sequencer/resources/versioned_constants.json
crates/sequencer/src/resources/versioned_constants.json

The execution of a transaction is bounded by two constraints:
- The amount of steps available in the environment - a hard limit that, if reached, will stop the execution ungracefully
- The amount of __gas__ (similar to EVM Gas) available in the environment - if reached, the execution will be stopped gracefully.
In the verisoned_constants.json file, we update the max steps limit, without updating the gas limit. This lead to tests that would fail because reaching an 'Out of gas' limit, different from a hard step limit.

chore: bump tx gas available in transactions

---

Makefile
scripts/generate_skip_file.py

Updates test fixtures with some pyspec tests refilled to avoid conflicts with precompile 0x100

dev: update test fixtures

---

crates/ef-testing/src/evm_sequencer/evm_state/mod.rs

uses the value inside the `current_block` index of the Kakarot_base_fee storage var as the base fee to use when running test.

feat: update base_fee storage location mirroring kakarot new strategy
