kkrt-labs/ef-tests

- .github/PULL_REQUEST_TEMPLATE.md
- Cargo.lock
- Cargo.toml
- crates/ef-testing/Cargo.toml
- crates/ef-testing/src/lib.rs
Add the initial rust crates imports for the project + pull request template
> feat: initial crate imports

- crates/ef-testing/src/constants.rs
- crates/ef-testing/src/lib.rs
- crates/ef-testing/src/models/case.rs
- crates/ef-testing/src/models/mod.rs
- crates/ef-testing/src/utils/assert.rs
Update the way tests are ran in order to include all test cases for each file.
Resolves: #12
-   [x] Bugfix
All test cases get loaded for each file.
-   [ ] Yes
-   [x] No
> fix: load cases

- .gitignore
- Cargo.lock
- Cargo.toml
- Makefile
- crates/ef-testing/Cargo.toml
- crates/ef-testing/src/models/case.rs
- crates/ef-testing/src/utils/assert.rs
- crates/ef-testing/tests/tests.rs
- Allows to run a specific test file or set of tests with regexp.
- Updates the tracing to avoid logging `jsonrpsee`.
- Corrects the assertion display to use the same type, hence displaying both values in hex.
Time spent on this PR: 0.3 days
Resolves: #NA
-   [ ] Bugfix
-   [x] Refactoring (no functional changes, no API changes)
Cleans the current use of the tests
-   [ ] Yes
-   [x] No
> feat: improve test running

- Makefile
Time spent on this PR: 0
Resolves:
-   [X] Bugfix
`make setup` now works for fresh install
-   [ ] Yes
-   [X] No
> dev: add `EF_TESTS_DIR` as target

- .gitignore
- crates/ef-testing/src/models/mod.rs
Resolves: #24 
-   [X] Bugfix
Should be able to run tests i.e. `stSStoreTest` without deserialization error
-   [ ] Yes
-   [X] No
> dev: fix deserialization error

- crates/ef-testing/src/lib.rs
- crates/ef-testing/src/traits/mod.rs
Resolves: #23 
-   [ ] Bugfix
There is a `should_skip()` function which can be called with a path, and it can return whether a test should be ignored or not.
-   [ ] Yes
-   [x] No
> dev: add function to allow skipping tests

- .github/ISSUE_TEMPLATE/01_BUG_REPORT.md
- .github/ISSUE_TEMPLATE/02_FEATURE_REQUEST.md
- .github/ISSUE_TEMPLATE/03_CODEBASE_IMPROVEMENT.md
- .github/ISSUE_TEMPLATE/config.yml
Adds template for issues and bugs.
Resolves: #NA
-   [ ] Bugfix
We have templates for issues and bugs.
-   [ ] Yes
-   [x] No
> feat: templates

- crates/ef-testing/src/models/case.rs
- crates/ef-testing/src/models/result.rs
- crates/ef-testing/src/utils/assert.rs
Improves the logging in ef-tests based on a raised issue.
Resolves: #44 
-   [ ] Bugfix
Improves the logging by removing redunded phrasing, adding line breaks and displaying the failing evm_address.
-   [ ] Yes
-   [x] No
> feat: improve logging in ef-tests

- Cargo.lock
- Makefile
- crates/ef-testing/Cargo.toml
- crates/ef-testing/src/bin/fetch_commit_kakarot.rs
- crates/ef-testing/src/bin/fetch_dump_katana.rs
- crates/ef-testing/tests/tests.rs
Improves the information passed to users on the commit used in Katana for Kakarot.
Resolves: #47 
-   [ ] Bugfix
The makefile will now always pull the latest commit used on the Kakarot-rpc repo for building the Katana dump and compare it to the local dump used.
-   [ ] Yes
-   [x] No
> feat: improve logging info kakarot commit

- Cargo.lock
- Cargo.toml
- crates/ef-testing/Cargo.toml
- crates/ef-testing/src/lib.rs
- crates/ef-testing/src/models/case.rs
- crates/ef-testing/src/models/error.rs
- crates/ef-testing/src/models/mod.rs
- crates/ef-testing/src/models/result.rs
- crates/ef-testing/src/storage/contract.rs
- crates/ef-testing/src/storage/eoa.rs
- crates/ef-testing/src/storage/mod.rs
- crates/ef-testing/src/traits/mod.rs
- crates/ef-testing/src/utils/assert.rs
- crates/ef-testing/src/utils/io.rs
- crates/ef-testing/src/utils/starknet.rs
Remove al the `unwraps` and as much as possible of the `map_err` in the codebase.
Resolves: #59
-   [ ] Bugfix
Introduces a custom `RunnerError` enum and uses it to remove all unwraps and as much as possible the `map_err`.
-   [ ] Yes
-   [x] No
> feat: improve error handling

- README.md
- crates/ef-testing/src/models/case.rs
- crates/ef-testing/src/storage/mod.rs
- crates/ef-testing/src/utils/assert.rs
Fixes asserting on a non deployed contract.
Resolves: #56 
-   [x] Bugfix
Runner will now assert that a undeployed contract as an empty post state and the correct balance.
-   [ ] Yes
-   [x] No
> fix: assert empty state

- crates/ef-testing/src/models/case.rs
Resolves: #65 
-   [ ] Bugfix
-   [x] Refactoring (no functional changes, no API changes)
Improved logging for failures cases in post storage as described in #65 .
-   [ ] Yes
-   [x] No
> dev: improve logging for post state failures

- crates/ef-testing/src/lib.rs
- crates/ef-testing/src/models/case.rs
- crates/ef-testing/src/storage/contract.rs
- crates/ef-testing/src/storage/eoa.rs
- crates/ef-testing/src/storage/fee_token.rs
- crates/ef-testing/src/storage/mod.rs
- crates/ef-testing/src/storage/models.rs
Remove mutables as inputs of functions
Time spent on this PR: 0.4 day
Resolves: #64 
-   [ ] Bugfix
-   [x] Refactoring (no functional changes, no API changes)
Mutable inputs have been removed from the codebase (except for `write_test_state` where the `RwLock` needs to be mutable).
-   [ ] Yes
-   [x] No
> dev: remove mut

- crates/ef-testing/src/storage/mod.rs
Resolves: #41 
-   [X] Bugfix
For EOA accounts, we both check that it has no code nor storage
-   [ ] Yes
-   [X] No
> dev: fix handling pre-state to use correct implementation class hash

- .github/workflows/linters.yml
- .github/workflows/test.yml
Resolves: #<Issue number>
-   [ ] Bugfix
run system tests, not the EF tests themselves
-   [ ] Yes
-   [X] No
> let there be ci

- Cargo.lock
- Cargo.toml
- crates/ef-testing/Cargo.toml
- crates/ef-testing/src/models/case.rs
- crates/ef-testing/src/models/error.rs
- crates/ef-testing/src/storage/contract.rs
- crates/ef-testing/src/storage/eoa.rs
- crates/ef-testing/src/storage/fee_token.rs
- crates/ef-testing/src/storage/mod.rs
- crates/ef-testing/src/utils/assert.rs
- crates/ef-testing/tests/tests.rs
Bump the Katana dep and RPC deps.
Time spent on this PR: 2 days
Resolves: #NA
-   [ ] Bugfix
The katana dep and RPC dep is bumped.
-   [ ] Yes
-   [x] No
> feat: bump katana

- crates/ef-testing/src/models/case.rs
- crates/ef-testing/tests/tests.rs
-   [ ] Bugfix
-   [ ] Yes
-   [x] No
> feat: add stSolidityTest test suite

- README.md
Time spent on this PR: 2h
Resolves: #129 
-   [ ] Bugfix
-   [x] Documentation content changes
-   [ ] Yes
-   [x] No
> Doc: Add Github token requirments in README.md

- .devcontainer/devcontainer.json
Time spent on this PR: 1h
Resolves: N/A
-   [ ] Bugfix
Add devcontainer settings to simplify setup
-   [ ] Yes
-   [x] No
> feat: add devcontainer settings

- crates/ef-testing/src/models/case.rs
- crates/ef-testing/tests/tests.rs
Time spent on this PR: 1h30
Resolves: #87 #151 #152 
-   [ ] Bugfix
-   [ ] Yes
-   [x] No
> feat: add Shanghai testsuite

- crates/ef-testing/src/models/case.rs
- crates/ef-testing/tests/tests.rs
Time spent on this PR: 3H
-   [ ] Bugfix
-   [ ] Yes
-   [ ] No
> Add: stExtCodeHash to the blockchain tests module

- crates/ef-testing/tests/tests.rs
Resolves: #<Issue number>
-   [ ] Bugfix
-   [X] Refactoring (no functional changes, no API changes)
-   [ ] Yes
-   [ ] No
> Organize tests to have better organization and visility

- blockchain-tests-skip.yml
Resolves: #<Issue number>
-   [x] Bugfix
-   [ ] Yes
-   [x] No
> fix: fix CI and skipped tests missed in rebase

- blockchain-tests-skip.yml
- crates/ef-testing/tests/tests.rs
Time spent on this PR: 20m
#259 
-   [ ] Bugfix
-   [ ] Yes
-   [x] No
> feat: add `stAttackTest` testsuite to the blockchain_tests module

- crates/ef-testing/tests/tests.rs
Time spent on this PR: 5m
`stCodeCopyTest` and `stCodeSizeLimit` are already merged by #266 
-   [ ] Bugfix
-   [ ] Yes
-   [x] No
> fix rebase regression (`stCodeCopyTest` and `stCodeSizeLimit`)

- blockchain-tests-skip.yml
- crates/ef-testing/tests/tests.rs
#92 
-   [ ] Bugfix
-   [ ] Yes
-   [x] No
> feat: add `stChainId` to the blockchain tests module

- blockchain-tests-skip.yml
- crates/ef-testing/tests/tests.rs
#302 
-   [ ] Bugfix
-   [ ] Yes
-   [x] No
> feat: add `stEIP150Specific` testsuite to the blockchain_tests module

- blockchain-tests-skip.yml
- crates/ef-testing/tests/tests.rs
Time spent on this PR: 0.2
-   [ ] Bugfix
-   [ ] Yes
-   [x] No
> Added stReturnDataTest

- blockchain-tests-skip.yml
- crates/ef-testing/tests/tests.rs
Time spent on this PR: 0.2
- 23 failed tests
Created issues:
- https://github.com/kkrt-labs/ef-tests/issues/322
- https://github.com/kkrt-labs/ef-tests/issues/323
- https://github.com/kkrt-labs/ef-tests/issues/324
-   [ ] Bugfix
-   [ ] Yes
-   [X] No
> stRevertTest tests implementation

- blockchain-tests-skip.yml
- crates/ef-testing/tests/tests.rs
Time spent on this PR: 15m
#347 
-   [ ] Bugfix
-   [ ] Yes
-   [x] No
> add `stHomesteadSpecific` testsuite

- blockchain-tests-skip.yml
- crates/ef-testing/tests/tests.rs
#348 
-   [ ] Bugfix
-   [ ] Yes
-   [x] No
> add `stMemExpandingEIP150Calls` testsuite

- blockchain-tests-skip.yml
- crates/ef-testing/tests/tests.rs
Time spent on this PR: 15m
#346 
-   [ ] Bugfix
-   [ ] Yes
-   [x] No
> add `stEIP158Specific` testsuite

- crates/ef-testing/tests/tests.rs
#454 #456 #457
-   [ ] Bugfix
-   [ ] Yes
-   [x] No
> Add tests failing due to missing field gasPrice

- crates/ef-testing/src/models/result.rs
- crates/ef-testing/tests/tests.rs
Resolves: #NA
-   [x] Bugfix
Fix the error logging of Katana and remove unnecessary logging.
-   [ ] Yes
-   [x] No
> fix: improve logging

- blockchain-tests-skip.yml
- crates/ef-testing/tests/tests.rs
Time spent on this PR: 15min
#432 
-   [ ] Bugfix
-   [ ] Yes
-   [x] No
> add `stTransitionTest` testsuite

- blockchain-tests-skip.yml
- crates/ef-testing/tests/tests.rs
Time spent on this PR: 30min
#449 
-   [ ] Bugfix
-   [ ] Yes
-   [x] No
> add `stSystemOperationsTest` testsuite

- .github/workflows/test.yml
- crates/ef-testing/tests/tests.rs
- Refactoring tests order 
- Deleted duplicates (some had comments and tests)
- Increased tests timeout limit
Time spent on this PR: 10 mins
-   [ ] Bugfix
-   [X] Refactoring (no functional changes, no API changes)
-   [ ] Yes
-   [ ] No
> Refactoring tests order and tests timeout limit

- crates/ef-testing/src/evm_sequencer/constants.rs
- crates/ef-testing/src/evm_sequencer/evm_state.rs
- crates/ef-testing/src/evm_sequencer/mod.rs
Resolves: #NA
Fee token is deployed in the initialization of the sequencer. Also adds some helpers in order to access evm storage and nonce.
> fix: kakarot sequencer

- README.md
> Remove useless make command since Katana deprecation

- crates/ef-testing/src/models/result.rs
- crates/ef-testing/src/traits/mod.rs
Resolves: #NA
Re-add some logging for just the failing tests.
> fix: logging

- .vscode/settings.json
Time spent on this PR: 0.01
Added some spellings
> Add spellings

- .env.example
- .gitignore
- Makefile
- blockchain-tests-skip.yml
- crates/ef-testing/Cargo.toml
- crates/ef-testing/src/models/case.rs
- crates/ef-testing/src/models/result.rs
- crates/ef-testing/src/traits/mod.rs
- crates/ef-testing/tests/tests.rs
Resolves: #522 
The transaction cost of the sender is subtracted from his balance, allowing to assert on the balance of the sender address.
> feat: balance verification sender

- .devcontainer/devcontainer.json
Since #488, poetry is no longer mandatory
> dev: Remove useless dependencies in devcontainer

- .env.example
the `.env.example` file has been removed, but since #488 `GITHUB_TOKEN` is used to pull Kakarot build artifacts.
Time spent on this PR: 5m
> dev: Add `.env.example` file

- .config/nextest.toml
- Makefile
- crates/ef-testing/src/models/case.rs
- crates/ef-testing/src/traits/mod.rs
- crates/ef-testing/tests/tests.rs
Improve the logs by displaying all failing output at the end of all tests. Also only deserialize test files that are not skipped.
> dev: improve logging and loading

- .github/workflows/test.yml
- .trunk/trunk.yaml
- Cargo.lock
- Cargo.toml
- Makefile
- README.md
- crates/ef-testing/Cargo.toml
- crates/ef-testing/tests/tests.rs
- crates/sequencer/src/sequencer.rs
- scripts/compute_resources.py
Time spent on this PR: 1 day
Resolves: #553 
This allows to save an artifact of the test resources as a csv.
> feat: resource usage

- .devcontainer/devcontainer.json
- .github/workflows/test.yml
- Makefile
- README.md
- crates/ef-testing/src/evm_sequencer/mod.rs
- crates/ef-testing/src/models/case.rs
- crates/ef-testing/src/models/mod.rs
- crates/ef-testing/src/models/result.rs
- crates/ef-testing/tests/tests.rs
- crates/sequencer/src/execution.rs
- crates/sequencer/src/sequencer.rs
- scripts/compute_resources.py
Resolves: #NA
Clean the current log output
> feat: update logs

- .trunk/trunk.yaml
- crates/ef-testing-proc-macros/src/constants.rs
- crates/ef-testing-proc-macros/src/content_reader.rs
- crates/ef-testing-proc-macros/src/converter.rs
- crates/ef-testing-proc-macros/src/dir_reader.rs
- crates/ef-testing-proc-macros/src/filter.rs
- crates/ef-testing-proc-macros/src/lib.rs
- crates/ef-testing-proc-macros/src/utils.rs
- crates/ef-testing/src/evm_sequencer/evm_state.rs
- crates/ef-testing/src/evm_sequencer/types.rs
- crates/ef-testing/src/evm_sequencer/utils.rs
- crates/ef-testing/src/models/case.rs
- crates/sequencer/src/transaction.rs
> fix: all clippy::all and clippy::nursery

- .trunk/trunk.yaml
- blockchain-tests-skip.yml
- crates/ef-testing-proc-macros/src/content_reader.rs
- crates/ef-testing-proc-macros/src/converter.rs
- crates/ef-testing/src/evm_sequencer/constants.rs
- crates/ef-testing/src/lib.rs
- crates/ef-testing/src/models/case.rs
- crates/ef-testing/src/models/error.rs
Time spent on this PR: 0.4 day
Resolves: #NA
Skips additional tests in order to work with the updated Kakarot contract. Adds reason for skipping tests and skips malformed tests files. Adds better error formatting.
> fix: test skipping

- blockchain-tests-skip.yml
- crates/ef-testing/src/lib.rs
Resolves: #NA
Fix the RLP encoding to remove the header.
> fix: rlp encoding

- .vscode/settings.json
- blockchain-tests-skip.yml
Time spent on this PR: 0.2
Skip tests previously passing but failing for the KKT0 stack update.
> Skip tests for Stack refacto

- blockchain-tests-skip.yml
> fix: uncomment passing tests

- blockchain-tests-skip.yml
> Skip tests for Arithmetic ops OOG PR

- blockchain-tests-skip.yml
- crates/ef-testing/src/lib.rs
Time spent on this PR: 0.3 day 
Resolves: #585 
Legacy txs are matched against and the chain ID is updated in order to avoid rlp decding errors.
> dev: update runner to handle pre eip 155 txs

- blockchain-tests-skip.yml
Time spent on this PR: 0.3
Passing while failing before due to EVM error.
To be merged after https://github.com/kkrt-labs/kakarot/pull/805
> Unskip some SELFDESTRUCT tests

- blockchain-tests-skip.yml
Resolves: #NA
Remove skipping of exp passed test.
> fix: unlock test from exp update

- blockchain-tests-skip.yml
Time spent on this PR: 1day 
Took me some time but I finally understand  ef-tests better ! 
all these tests are skipped because of OOG
> feat: add tests that fail because of gas

- blockchain-tests-skip.yml
> Skip OOG in SELFDESTRUCT

- blockchain-tests-skip.yml
Previously passing with Cairo VM error
> Skip memory test with OOG

- crates/build-utils/src/filter.rs
- crates/ef-testing/src/evm_sequencer/account.rs
- crates/ef-testing/src/evm_sequencer/evm_state.rs
- crates/ef-testing/src/evm_sequencer/mod.rs
- crates/ef-testing/src/models/case.rs
- crates/ef-testing/src/models/result.rs
Resolves: #589 
Split the responsibility of converting the evm account status into the Kakarot account state and writing this state to starknet.
> dev: deploy empty contract account

- crates/ef-testing/src/evm_sequencer/utils.rs
- crates/ef-testing/src/models/result.rs
Resolves: #NA
Remove the clippy warnings when compiling with features flags v0 or v1.
Also fix the revert message logging.
> fix: clippy warnings

- blockchain-tests-skip.yml
- scripts/compute_resources.py
> Skip tests for memory expansion

- blockchain-tests-skip.yml
Resolves: #NA
Skip all the run resources reached tests.
> feat: skip test running out of resources

- blockchain-tests-skip.yml
- crates/build-utils/src/converter.rs
- crates/ef-testing/src/models/case.rs
- crates/ef-testing/src/models/result.rs
> dev: add folder name to logging

- blockchain-tests-skip.yml
Need to skip for https://github.com/kkrt-labs/kakarot/pull/840 fixing some of these errors
> Skip some false positive raising maximum offset value exceeded

- crates/build-utils/src/constants.rs
- crates/build-utils/src/converter.rs
- crates/build-utils/src/dir_reader.rs
- crates/build-utils/src/filter.rs
- crates/ef-testing/build.rs
- crates/ef-testing/src/evm_sequencer/account/mod.rs
- crates/ef-testing/src/evm_sequencer/account/v0.rs
- crates/ef-testing/src/evm_sequencer/account/v1.rs
- crates/ef-testing/src/evm_sequencer/evm_state/mod.rs
- crates/ef-testing/src/evm_sequencer/evm_state/v0.rs
- crates/ef-testing/src/evm_sequencer/evm_state/v1.rs
- crates/ef-testing/src/evm_sequencer/sequencer/mod.rs
- crates/ef-testing/src/evm_sequencer/types/contract_class.rs
- crates/ef-testing/src/evm_sequencer/utils.rs
- crates/ef-testing/src/models/case.rs
- crates/ef-testing/src/models/error.rs
- crates/ef-testing/src/models/result.rs
- crates/ef-testing/src/traits/mod.rs
- crates/ef-testing/src/utils/mod.rs
Resolves: #NA
Refactors some parts of the code by:
- Renaming
- Removing unnecessary traits or error variants
- Add helpful macro for starknet storage 
- Improves the API for some of the types
> dev: cleaning

- Cargo.lock
- Cargo.toml
Time spent on this PR: 1 day
Resolves: #NA
Printing can now be used in the ef-tests execution. The available hints for printing are listed here:
https://github.com/kkrt-labs/cairo-vm/blob/main/vm/src/hint_processor/builtin_hint_processor/hint_code.rs#L1413-L1423
In order to have a display appear, you need to run tests with `cargo test --features v0 -- --nocapture`
> dev: bump compiler and cairo-vm

- .github/workflows/test.yml
- Makefile
- scripts/compute_resources.py
Resolves: #NA
Tests are ran from the CI, python script is only used to retrieve the resources.
> dev: update the way tests are ran and resources extracted

- crates/ef-testing/src/evm_sequencer/evm_state/v1.rs
Resolves: #NA
Fixes the hash used to fetch the nonce in contract account storage.
> fix: nonce v1

- scripts/generate_skip_file.py
Not sure why but the first match was skipped. I added a check to make sure that returned list length is number of failed tests in the summary..
> Fix generate skip file script

- scripts/generate_skip_file.py
Replace patterns also in test name
> Fix symbol in test name

- .github/workflows/test.yml
- .gitignore
- crates/ef-testing/src/evm_sequencer/account/v0.rs
- crates/ef-testing/src/evm_sequencer/constants.rs
- crates/ef-testing/src/evm_sequencer/evm_state/v0.rs
- crates/ef-testing/src/evm_sequencer/evm_state/v1.rs
- crates/ef-testing/src/evm_sequencer/sequencer/mod.rs
- crates/ef-testing/src/evm_sequencer/utils.rs
- crates/ef-testing/src/models/case.rs
- crates/sequencer/src/sequencer.rs
Time spent on this PR: 0.4 day
Resolves: #630, #629 and #615
Refactor the code and add approval of coinbase address for Kakarot.
> dev: improve ef-tests code

- crates/ef-testing/src/evm_sequencer/sequencer/mod.rs
Resolves: #NA
Increases the step limit.
> feat: increase execution limits

- crates/build-utils/src/lib.rs
- crates/ef-testing/src/models/case.rs
- crates/ef-testing/src/models/result.rs
Resolves: #NA
Fixes the update brought to the failing tests in the ef-tests json files.
> fix: header

- crates/ef-testing/src/models/case.rs
Resolves: #NA
Fixes the incorrect coinbase balance.
> fix coinbase balance

- crates/ef-testing/src/models/case.rs
Resolves: #NA
Fixes the gas price issue when running EIP1559 txs.
> fix: gas price

- Cargo.lock
Resolves: #NA
Can use the print.
> feat: bump blockifier to include the print feature

- Makefile
- crates/ef-testing/src/evm_sequencer/constants.rs
- crates/ef-testing/src/evm_sequencer/sequencer/mod.rs
- crates/ef-testing/src/evm_sequencer/sequencer/v0.rs
- crates/ef-testing/src/evm_sequencer/sequencer/v1.rs
Resolves: #641 
Precompiles contract is declared for v0 feature.
> feat: deploy precompiles 

- crates/ef-testing/src/evm_sequencer/account/v0.rs
- crates/ef-testing/src/evm_sequencer/evm_state/v0.rs
- crates/ef-testing/src/evm_sequencer/utils.rs
Update the way bytecode is stored.
> feat: update bytecode storage

- .github/workflows/test.yml
- crates/ef-testing/src/evm_sequencer/account/mod.rs
- crates/ef-testing/src/evm_sequencer/account/v0.rs
- crates/ef-testing/src/evm_sequencer/account/v1.rs
- crates/ef-testing/src/evm_sequencer/evm_state/v0.rs
- crates/ef-testing/src/evm_sequencer/utils.rs
Resolves: #NA
Updates the way the bytecode is packed from 16 bytes packed to 31 bytes packed.
> feat: update bytecode packing

- .github/workflows/test.yml
- Cargo.lock
- Cargo.toml
- crates/build-utils/src/converter.rs
- crates/ef-testing/Cargo.toml
- crates/ef-testing/src/evm_sequencer/account/mod.rs
- crates/ef-testing/src/evm_sequencer/account/v0.rs
- crates/ef-testing/src/evm_sequencer/account/v1.rs
- crates/ef-testing/src/evm_sequencer/constants.rs
- crates/ef-testing/src/evm_sequencer/evm_state/mod.rs
- crates/ef-testing/src/evm_sequencer/evm_state/v0.rs
- crates/ef-testing/src/evm_sequencer/evm_state/v1.rs
- crates/ef-testing/src/evm_sequencer/utils.rs
- crates/ef-testing/src/models/case.rs
- crates/ef-testing/src/models/error.rs
- crates/ef-testing/src/models/mod.rs
- crates/ef-testing/src/utils/mod.rs
- crates/sequencer/src/transaction.rs
- rust-toolchain
Resolves: #NA
Reth is bumped to the latest tag.
> dev: bump reth

- crates/ef-testing/src/evm_sequencer/constants.rs
- crates/ef-testing/src/evm_sequencer/sequencer/v1.rs
Resolves: #NA
Remove the ssj deploy fee.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/ef-tests/654)
> feat: remove deploy fee

- crates/ef-testing/src/evm_sequencer/account/mod.rs
- crates/ef-testing/src/evm_sequencer/account/v0.rs
- crates/ef-testing/src/evm_sequencer/account/v1.rs
- crates/ef-testing/src/evm_sequencer/evm_state/v0.rs
- crates/ef-testing/src/evm_sequencer/evm_state/v1.rs
Resolves: #NA
Getters for the KakarotAccount.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/ef-tests/656)
> feat: getters

- crates/ef-testing/src/evm_sequencer/evm_state/mod.rs
- crates/ef-testing/src/evm_sequencer/evm_state/v0.rs
- crates/ef-testing/src/evm_sequencer/evm_state/v1.rs
- crates/ef-testing/src/models/case.rs
> feat: set prevrandao and block gaslimit

- crates/ef-testing/src/evm_sequencer/constants.rs
- crates/ef-testing/src/evm_sequencer/evm_state/v0.rs
- crates/ef-testing/src/evm_sequencer/evm_state/v1.rs
- crates/ef-testing/src/evm_sequencer/sequencer/v0.rs
- crates/ef-testing/src/evm_sequencer/sequencer/v1.rs
- crates/ef-testing/src/models/case.rs
- crates/ef-testing/src/models/result.rs
Time spent on this PR: 0.3d
Uses the output from the run to retrieve the `gas_used` value, instead of using the value from the block header.
> feat: check run output gas_used

- crates/ef-testing/src/models/case.rs
- scripts/generate_skip_file.py
Time spent on this PR: 0.1d
- Adapted utils to generate skipfile with failure reason in comment if it's a runresources error
- If a test fails and there's a revert reason - print it.
> chore: show RunResources in test-skip.yml, print revert reason in test

- crates/ef-testing/src/models/case.rs
Time spent on this PR: 0.1d
Verify that the actual sender balance matches the expected one, and the the correct amount has been charged to pay for the gas.
> feat: verify sender's balance

- Cargo.lock
- crates/ef-testing/src/models/case.rs
Resolves: #NA
Updates the lock to point to the new commits of the cairo vm and blockifier forks.
> fix: update lock

- Cargo.lock
- Cargo.toml
- Makefile
- crates/build-utils/src/filter.rs
- crates/ef-testing/src/evm_sequencer/constants.rs
- crates/ef-testing/src/evm_sequencer/evm_state/v0.rs
- crates/ef-testing/src/evm_sequencer/evm_state/v1.rs
- crates/ef-testing/src/evm_sequencer/sequencer/mod.rs
- crates/ef-testing/src/evm_sequencer/sequencer/v0.rs
- crates/ef-testing/src/evm_sequencer/sequencer/v1.rs
- crates/ef-testing/src/models/case.rs
- crates/sequencer/src/commit.rs
- crates/sequencer/src/sequencer.rs
- crates/sequencer/src/serde.rs
- crates/sequencer/src/state.rs
Time spent on this PR: 2 days
Resolves: #NA
Some optimizations on the allocation of memory on the heap + bump of deps.
> dev: bump deps

- crates/ef-testing/src/evm_sequencer/account/mod.rs
- crates/ef-testing/src/evm_sequencer/account/v0.rs
- crates/ef-testing/src/evm_sequencer/constants.rs
- crates/ef-testing/src/evm_sequencer/evm_state/v0.rs
- crates/ef-testing/src/evm_sequencer/evm_state/v1.rs
- crates/ef-testing/src/evm_sequencer/sequencer/mod.rs
- crates/ef-testing/src/evm_sequencer/sequencer/v0.rs
- crates/ef-testing/src/evm_sequencer/sequencer/v1.rs
- crates/ef-testing/src/models/case.rs
Time spent on this PR: 0.6d
Resolves: #687
> refactor: v0 account model

- Cargo.lock
- crates/build-utils/src/content_reader.rs
- crates/build-utils/src/dir_reader.rs
- crates/build-utils/src/filter.rs
- crates/build-utils/src/path.rs
- crates/build-utils/src/utils.rs
- crates/ef-testing/src/evm_sequencer/constants.rs
- crates/ef-testing/src/evm_sequencer/types/felt.rs
- crates/ef-testing/src/evm_sequencer/utils.rs
Time spent on this PR: 45 min
Some enhancements and simplifications globally.
> Some enhancements

- crates/ef-testing/src/evm_sequencer/utils.rs
> feat: deploy from zero

- Makefile
> dev: remove ca/eoa from ssj makefile

- crates/ef-testing/src/evm_sequencer/constants.rs
- crates/ef-testing/src/evm_sequencer/evm_state/v0.rs
- crates/ef-testing/src/evm_sequencer/evm_state/v1.rs
- crates/ef-testing/src/evm_sequencer/sequencer/mod.rs
- crates/ef-testing/src/models/case.rs
> feat: set cairo1helpers account storage

- Cargo.lock
- Cargo.toml
- crates/ef-testing/Cargo.toml
- crates/ef-testing/src/evm_sequencer/constants.rs
- crates/ef-testing/src/evm_sequencer/evm_state/v0.rs
- crates/ef-testing/src/evm_sequencer/evm_state/v1.rs
Time spent on this PR: 30 min
Remove ruint as a dependency.
> Remove ruint as a dependency

- Cargo.lock
- Cargo.toml
Time spent on this PR: 30 min
Update crate versions in `Cargo.toml` file.
> Update crate versions in `Cargo.toml` file

- Cargo.lock
- Cargo.toml
Time spent on this PR: 10 min
Bump `reth` to `v0.2.0-beta.6`.
> Bump `reth` to `v0.2.0-beta.6`

- crates/ef-testing/src/evm_sequencer/account/mod.rs
- crates/ef-testing/src/evm_sequencer/account/v1.rs
- crates/ef-testing/src/evm_sequencer/constants.rs
- crates/ef-testing/src/evm_sequencer/evm_state/v0.rs
- crates/ef-testing/src/evm_sequencer/evm_state/v1.rs
- crates/ef-testing/src/evm_sequencer/sequencer/mod.rs
- crates/ef-testing/src/evm_sequencer/sequencer/v0.rs
- crates/ef-testing/src/evm_sequencer/sequencer/v1.rs
- crates/ef-testing/src/evm_sequencer/utils.rs
- crates/ef-testing/src/models/case.rs
- crates/ef-testing/src/models/result.rs
> feat: restore support for SSJ

- Makefile
> fix ssj makefile

- Makefile
- crates/ef-testing/ethereum-tests/BlockchainTests/GeneralStateTests/VmTests/vmArithmeticTest/add.json
- crates/ef-testing/ethereum-tests/BlockchainTests/GeneralStateTests/VmTests/vmArithmeticTest/mul.json
- crates/ef-testing/ethereum-tests/GeneralStateTests/VmTests/vmArithmeticTest/add.json
- crates/ef-testing/ethereum-tests/GeneralStateTests/VmTests/vmArithmeticTest/mul.json
> dev: update makefile

- Cargo.lock
- Cargo.toml
- crates/ef-testing/Cargo.toml
- crates/ef-testing/src/evm_sequencer/account/mod.rs
- crates/ef-testing/src/evm_sequencer/account/v0.rs
- crates/ef-testing/src/evm_sequencer/account/v1.rs
- crates/ef-testing/src/evm_sequencer/constants.rs
- crates/ef-testing/src/evm_sequencer/evm_state/v0.rs
- crates/ef-testing/src/evm_sequencer/evm_state/v1.rs
- crates/ef-testing/src/models/case.rs
Time spent on this PR:0.1d
Stores the jumpdests in the account storage when setting up an account.
> feat: store jumpdests on setup

- Cargo.lock
- Cargo.toml
- crates/ef-testing/src/evm_sequencer/evm_state/v0.rs
- rust-toolchain
> bump reth to `v0.2.0-beta.7`

- Cargo.lock
- Makefile
- crates/build-utils/Cargo.toml
- crates/build-utils/src/content_reader.rs
- crates/build-utils/src/converter.rs
Time spent on this PR: 1d
Uses http://github.com/kkrt-labs/tests instead of ethereum/tests for the test source. These python tests in this repo have been modified to stop using address 0x100 in tests, which caused conflicts with rip 7212
> feat: use custom kakarot tests

- crates/ef-testing/src/evm_sequencer/utils.rs
Resolves: #NA
Uses a signature length of 6.
> feat: set kakarot signature length to 6

- crates/ef-testing/src/evm_sequencer/utils.rs
Resolves: #NA
Revert the signature length change.
> revert signature length update

- Cargo.lock
- Cargo.toml
- crates/ef-testing/src/evm_sequencer/account/v0.rs
> bump reth to v0.2.0-beta.8

- Cargo.lock
- Cargo.toml
- crates/build-utils/src/converter.rs
> bump reth to v1.0.0-rc.1

- .github/workflows/test.yml
- .github/workflows/trunk-check.yml
- Cargo.lock
- Cargo.toml
- crates/build-utils/src/converter.rs
- crates/ef-testing/Cargo.toml
- crates/ef-testing/src/evm_sequencer/evm_state/v0.rs
- crates/ef-testing/src/evm_sequencer/sequencer/mod.rs
- crates/ef-testing/src/evm_sequencer/sequencer/resources/versioned_constants.json
- crates/ef-testing/src/evm_sequencer/types/contract_class.rs
- crates/ef-testing/src/models/result.rs
- crates/sequencer/src/commit.rs
- crates/sequencer/src/resources/versioned_constants.json
- crates/sequencer/src/sequencer.rs
- crates/sequencer/src/state.rs
- rust-toolchain
> bump reth v1.0.0

- Cargo.lock
- Cargo.toml
> bump reth to 1.0.1

- crates/ef-testing/src/evm_sequencer/account/v0.rs
- crates/ef-testing/src/evm_sequencer/account/v1.rs
- crates/ef-testing/src/evm_sequencer/evm_state/v1.rs
- crates/ef-testing/src/evm_sequencer/types/felt.rs
- crates/sequencer/src/constants.rs
- crates/sequencer/src/transaction.rs
> cleanup some logic around Felt

- crates/ef-testing/src/evm_sequencer/account/v1.rs
- crates/ef-testing/src/evm_sequencer/evm_state/v0.rs
- crates/ef-testing/src/evm_sequencer/evm_state/v1.rs
- crates/ef-testing/src/evm_sequencer/sequencer/mod.rs
- crates/sequencer/src/constants.rs
- crates/sequencer/src/sequencer.rs
> some refactor around Felt

- crates/ef-testing/src/utils/mod.rs
> utils: refactor `update_post_state` and add unit tests

- crates/ef-testing/src/evm_sequencer/evm_state/v0.rs
- crates/ef-testing/src/evm_sequencer/evm_state/v1.rs
- crates/ef-testing/src/models/case.rs
- crates/sequencer/src/transaction.rs
> some refactor around `From` `Felt`

- Cargo.lock
- Cargo.toml
> bump blockifier to have test_utils cairo vm

- crates/ef-testing/src/evm_sequencer/evm_state/v0.rs
- crates/ef-testing/src/evm_sequencer/sequencer/mod.rs
- crates/ef-testing/src/evm_sequencer/utils.rs
Linked to https://github.com/kkrt-labs/kakarot/pull/1330
Account address calculation depends on Kakarot address.
> feat: change deploy from zero to false

- Cargo.lock
- Cargo.toml
> bump reth to 1.0.4

- crates/ef-testing/src/evm_sequencer/sequencer/resources/versioned_constants.json
- crates/sequencer/src/resources/versioned_constants.json
Restored the max invoke steps to 50M, it was wrongly changed by the previous PR.
> fix: restore invoke_tx_max_n_steps to 50M

- crates/ef-testing/src/evm_sequencer/account/mod.rs
- crates/ef-testing/src/evm_sequencer/evm_state/mod.rs
- crates/ef-testing/src/models/case.rs
> KakarotAccount: simplify new method using Account struct

- crates/ef-testing/src/evm_sequencer/sequencer/mod.rs
- crates/ef-testing/src/evm_sequencer/types/contract_class.rs
> Felt: refactor conversion from `Felt` to `BigUint`

- crates/ef-testing/src/evm_sequencer/sequencer/mod.rs
- Remove useless functions
- Refactor the implementation
> refactor `KakarotSequencer` impl

- Cargo.lock
- Cargo.toml
> bump starknet to 0.12

- crates/ef-testing/src/evm_sequencer/constants.rs
> update chain id to 1 -> ef-spec compliant

- Makefile
update test fixture with fixed version of eip7516_blobgasfee
> update test fixtures

- Makefile
Bumps version to fix problematic fixtures
> bump ef-test with re-gen fixtures
